services:
  birdnet-go:
    container_name: birdnet-go
    build: .
    ports:
      - "8080:8080"
    devices:
      - /dev/snd:/dev/snd
    environment:
      TZ: "Europe/Stockholm"
    volumes:
      - ./config:/config
      - ./data:/data
    depends_on:
      db:
        condition: service_healthy
    command: realtime
  db:
    image: mysql
    container_name: birdnet-go-db
    environment:
      MYSQL_ROOT_PASSWORD: ***
      MYSQL_DATABASE: birdnet
      MYSQL_USER: birdnet
      MYSQL_PASSWORD: ***
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
